### ISSUE TITLE
Error when running on fast_local or local on hydra 0.3.4

### ISSUE THREAD

**Issue by angeliney** [georgian-io/hydra#29]
Hi, I tried running on aws and it worked fine, but got the following error when running locally. 

When running with `--cloud fast_local`, got the following error:
```
Traceback (most recent call last):
  File "/Users/.../miniconda3/envs/.../bin/hydra", line 8, in <module>
    sys.exit(cli())
  File "/Users/.../miniconda3/envs/.../lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/angelineyasodhara/miniconda3/envs/.../lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/.../miniconda3/envs.../lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/.../miniconda3/envs/.../lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/.../miniconda3/envs/.../lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/.../miniconda3/envs/.../lib/python3.7/site-packages/hydra/cli.py", line 124, in train
    platform.train()
  File "/Users/.../miniconda3/envs/.../lib/python3.7/site-packages/hydra/cloud/fast_local_platform.py", line 9, in train
    os.system(" ".join([self.options, 'python3', self.model_path]))
TypeError: sequence item 0: expected str instance, dict found
```
Updating with `-o ""` also gives an error at `json.loads(options)` in `hydra/cli.py`.

When running with `--cloud local`, got the following error:
`sh: /Users/..../miniconda3/envs/..../lib/python3.7/site-packages/hydra/cloud/../../docker/local_execution.sh: No such file or directory
`

**Comment by tsa87** [comment]
Hi Angeline, thanks for reporting the bug! There's an issue with the variable name change in release/0.3.4; I made a [commit](https://github.com/georgianpartners/hydra/commit/7272dcbeeb2eee86cdfe924cc75a367a7282766d) on that branch. If you need the change now, maybe you could try to install hydra 0.3.4 from the source?

**Comment by angeliney** [comment]
Thank you for the quick solution, Tony! That fixed the `fast_local` setting, but still getting the same error for the `local` setting.

**Comment by tsa87** [comment]
I wasn't able to reproduce the error for the `local` setting.  But it seems like `docker/` and `resources/
` folders weren't installed along with `hydra` using `pip install hydra-ml`

**Comment by tsa87** [comment]
I moved these folders with`release/0.3.5`, that branch should solve the issue.

**Comment by angeliney** [comment]
Hi Tony, I'm not sure if that resolved the issue. I encountered another problem after re-trying with your solution when I re-installed hydra from source.
Instead of `/Users/<my_username>/miniconda3/envs/<my_env>/lib/python3.7/site-packages/hydra/cloud/../../docker/local_execution.sh`,
it is now looking for the docker files under `/Users/<my_username>/miniconda3/envs/<my_env>/lib/python3.7/site-packages/hydra_ml-0.3.5-py3.7.egg/hydra/cloud/../../docker/local_execution.sh`.

This is now making the pointer to the docker wrong since docker is in `site-packages` folder, but it's looking for it under `hydra_ml-0.3.4-py3.7.egg`

**Comment by coder46** [comment]
@angeliney I'm looking into this 👍

**Comment by coder46** [comment]
Looks like `0.3.5` still has an issue with `fast_local`
when i ran `hydra train -m model.py --cloud=fast_local` i got this stacktrace
```
(hydra) ➜  hydra-ml-projects git:(demo) hydra train -m model.py --cloud=fast_local

[Hydra Info]: Executing experiments with the following options: 
 [{}]


[Hydra Info]: Runnning experiment #0 with the following options: 
 {}

Traceback (most recent call last):
  File "/Users/faisalanees/.conda/envs/hydra/bin/hydra", line 33, in <module>
    sys.exit(load_entry_point('hydra-ml', 'console_scripts', 'hydra')())
  File "/Users/faisalanees/.conda/envs/hydra/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/faisalanees/.conda/envs/hydra/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/faisalanees/.conda/envs/hydra/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/faisalanees/.conda/envs/hydra/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/faisalanees/.conda/envs/hydra/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/faisalanees/work/hydra/hydra/cli.py", line 124, in train
    platform.train()
  File "/Users/faisalanees/work/hydra/hydra/cloud/fast_local_platform.py", line 9, in train
    os.system(" ".join([self.options, 'python3', self.model_path]))
TypeError: sequence item 0: expected str instance, dict found
```

**Comment by tsa87** [comment]
`Cloning into '.'...
remote: Invalid username or password.`
This issue seems to be caused from a invalid github authentication key.

**Comment by angeliney** [comment]
@coder46 I just updated to hydra 0.3.5 (installing from pip) and `fast_local` now works fine with options filled. Without options, I'm getting the following error, same as your error above:
Command: `hydra train -y tiny_run.yaml --cloud fast_local -o '{}'`
Stacktrace:
```
[Hydra Info]: Loading run info from tiny_run.yaml...
Traceback (most recent call last):
  File "/Users/angelineyasodhara/miniconda3/bin/hydra", line 8, in <module>
    sys.exit(cli())
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/hydra/cli.py", line 113, in train
    options_list_inflated = inflate_options(options_list)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/hydra/utils/utils.py", line 8, in inflate_options
    dictionary_list_inflated += dict_product(dictionary)
  File "/Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/hydra/utils/utils.py", line 20, in dict_product
    for key, values in dictionary.items():
AttributeError: 'str' object has no attribute 'items'
```

With local I'm still getting issue as before:
Command:
`hydra train -y tiny_run.yaml --cloud local`

Stacktrace:
```
[Hydra Info]: Loading run info from tiny_run.yaml...

[Hydra Info]: Executing experiments with the following options: 
 [{'batch_size': 1, 'epoch': 5, 'learning_rate': 0.0001}]


[Hydra Info]: Runnning experiment #0 with the following options: 
 {'batch_size': 1, 'epoch': 5, 'learning_rate': 0.0001}

sh: /Users/angelineyasodhara/miniconda3/lib/python3.7/site-packages/hydra/cloud/../docker/local_execution.sh: No such file or directory
```
